/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatgptPromptsRouteImport } from './routes/chatgpt-prompts'
import { Route as FreePromptsRouteImport } from './routes/free-prompts'
import { Route as GrantsAfricanWomenRouteImport } from './routes/grants-african-women'
import { Route as GrantsForWomenRouteImport } from './routes/grants-for-women'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MarketingPromptsRouteImport } from './routes/marketing-prompts'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MeetVictoriaRouteImport } from './routes/meet-victoria'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OpportunityCenterRouteImport } from './routes/opportunity-center'
import { Route as PitchTemplatesRouteImport } from './routes/pitch-templates'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRouteImport } from './routes/[.well-known]/apple-developer-merchantid-domain-association'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin-orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPromptVaultRouteImport } from './routes/_authenticated/prompt-vault'
import { Route as AuthenticatedPromptVaultAdminRouteImport } from './routes/_authenticated/prompt-vault-admin'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesThankYouRouteImport } from './routes/services.thank-you'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptPromptsRoute = ChatgptPromptsRouteImport.update({
  id: '/chatgpt-prompts',
  path: '/chatgpt-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePromptsRoute = FreePromptsRouteImport.update({
  id: '/free-prompts',
  path: '/free-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsAfricanWomenRoute = GrantsAfricanWomenRouteImport.update({
  id: '/grants-african-women',
  path: '/grants-african-women',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsForWomenRoute = GrantsForWomenRouteImport.update({
  id: '/grants-for-women',
  path: '/grants-for-women',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPromptsRoute = MarketingPromptsRouteImport.update({
  id: '/marketing-prompts',
  path: '/marketing-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetVictoriaRoute = MeetVictoriaRouteImport.update({
  id: '/meet-victoria',
  path: '/meet-victoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityCenterRoute = OpportunityCenterRouteImport.update({
  id: '/opportunity-center',
  path: '/opportunity-center',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchTemplatesRoute = PitchTemplatesRouteImport.update({
  id: '/pitch-templates',
  path: '/pitch-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute =
  Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRouteImport.update(
    {
      id: '/.well-known/apple-developer-merchantid-domain-association',
      path: '/.well-known/apple-developer-merchantid-domain-association',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin-orders',
    path: '/admin-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptVaultRoute =
  AuthenticatedPromptVaultRouteImport.update({
    id: '/prompt-vault',
    path: '/prompt-vault',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptVaultAdminRoute =
  AuthenticatedPromptVaultAdminRouteImport.update({
    id: '/prompt-vault-admin',
    path: '/prompt-vault-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesThankYouRoute = ServicesThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => ServicesRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatgpt-prompts': typeof ChatgptPromptsRoute
  '/free-prompts': typeof FreePromptsRoute
  '/grants-african-women': typeof GrantsAfricanWomenRoute
  '/grants-for-women': typeof GrantsForWomenRoute
  '/join': typeof JoinRoute
  '/marketing-prompts': typeof MarketingPromptsRoute
  '/mcp': typeof McpRoute
  '/meet-victoria': typeof MeetVictoriaRoute
  '/membership': typeof MembershipRoute
  '/opportunity-center': typeof OpportunityCenterRoute
  '/pitch-templates': typeof PitchTemplatesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prompt-vault': typeof AuthenticatedPromptVaultRoute
  '/prompt-vault-admin': typeof AuthenticatedPromptVaultAdminRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/services/thank-you': typeof ServicesThankYouRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatgpt-prompts': typeof ChatgptPromptsRoute
  '/free-prompts': typeof FreePromptsRoute
  '/grants-african-women': typeof GrantsAfricanWomenRoute
  '/grants-for-women': typeof GrantsForWomenRoute
  '/join': typeof JoinRoute
  '/marketing-prompts': typeof MarketingPromptsRoute
  '/mcp': typeof McpRoute
  '/meet-victoria': typeof MeetVictoriaRoute
  '/membership': typeof MembershipRoute
  '/opportunity-center': typeof OpportunityCenterRoute
  '/pitch-templates': typeof PitchTemplatesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prompt-vault': typeof AuthenticatedPromptVaultRoute
  '/prompt-vault-admin': typeof AuthenticatedPromptVaultAdminRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/services/thank-you': typeof ServicesThankYouRoute
  '/services': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chatgpt-prompts': typeof ChatgptPromptsRoute
  '/free-prompts': typeof FreePromptsRoute
  '/grants-african-women': typeof GrantsAfricanWomenRoute
  '/grants-for-women': typeof GrantsForWomenRoute
  '/join': typeof JoinRoute
  '/marketing-prompts': typeof MarketingPromptsRoute
  '/mcp': typeof McpRoute
  '/meet-victoria': typeof MeetVictoriaRoute
  '/membership': typeof MembershipRoute
  '/opportunity-center': typeof OpportunityCenterRoute
  '/pitch-templates': typeof PitchTemplatesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/toolkit': typeof ToolkitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/prompt-vault': typeof AuthenticatedPromptVaultRoute
  '/_authenticated/prompt-vault-admin': typeof AuthenticatedPromptVaultAdminRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/services/thank-you': typeof ServicesThankYouRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chatgpt-prompts'
    | '/free-prompts'
    | '/grants-african-women'
    | '/grants-for-women'
    | '/join'
    | '/marketing-prompts'
    | '/mcp'
    | '/meet-victoria'
    | '/membership'
    | '/opportunity-center'
    | '/pitch-templates'
    | '/press'
    | '/privacy'
    | '/refunds'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/toolkit'
    | '/.mcp/list-tools'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/.well-known/oauth-protected-resource'
    | '/admin-orders'
    | '/dashboard'
    | '/prompt-vault'
    | '/prompt-vault-admin'
    | '/checkout/success'
    | '/services/thank-you'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chatgpt-prompts'
    | '/free-prompts'
    | '/grants-african-women'
    | '/grants-for-women'
    | '/join'
    | '/marketing-prompts'
    | '/mcp'
    | '/meet-victoria'
    | '/membership'
    | '/opportunity-center'
    | '/pitch-templates'
    | '/press'
    | '/privacy'
    | '/refunds'
    | '/sitemap.xml'
    | '/terms'
    | '/toolkit'
    | '/.mcp/list-tools'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/.well-known/oauth-protected-resource'
    | '/admin-orders'
    | '/dashboard'
    | '/prompt-vault'
    | '/prompt-vault-admin'
    | '/checkout/success'
    | '/services/thank-you'
    | '/services'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chatgpt-prompts'
    | '/free-prompts'
    | '/grants-african-women'
    | '/grants-for-women'
    | '/join'
    | '/marketing-prompts'
    | '/mcp'
    | '/meet-victoria'
    | '/membership'
    | '/opportunity-center'
    | '/pitch-templates'
    | '/press'
    | '/privacy'
    | '/refunds'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/toolkit'
    | '/.mcp/list-tools'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin-orders'
    | '/_authenticated/dashboard'
    | '/_authenticated/prompt-vault'
    | '/_authenticated/prompt-vault-admin'
    | '/checkout/success'
    | '/services/thank-you'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatgptPromptsRoute: typeof ChatgptPromptsRoute
  FreePromptsRoute: typeof FreePromptsRoute
  GrantsAfricanWomenRoute: typeof GrantsAfricanWomenRoute
  GrantsForWomenRoute: typeof GrantsForWomenRoute
  JoinRoute: typeof JoinRoute
  MarketingPromptsRoute: typeof MarketingPromptsRoute
  McpRoute: typeof McpRoute
  MeetVictoriaRoute: typeof MeetVictoriaRoute
  MembershipRoute: typeof MembershipRoute
  OpportunityCenterRoute: typeof OpportunityCenterRoute
  PitchTemplatesRoute: typeof PitchTemplatesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolkitRoute: typeof ToolkitRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute: typeof Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt-prompts': {
      id: '/chatgpt-prompts'
      path: '/chatgpt-prompts'
      fullPath: '/chatgpt-prompts'
      preLoaderRoute: typeof ChatgptPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-prompts': {
      id: '/free-prompts'
      path: '/free-prompts'
      fullPath: '/free-prompts'
      preLoaderRoute: typeof FreePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants-african-women': {
      id: '/grants-african-women'
      path: '/grants-african-women'
      fullPath: '/grants-african-women'
      preLoaderRoute: typeof GrantsAfricanWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants-for-women': {
      id: '/grants-for-women'
      path: '/grants-for-women'
      fullPath: '/grants-for-women'
      preLoaderRoute: typeof GrantsForWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-prompts': {
      id: '/marketing-prompts'
      path: '/marketing-prompts'
      fullPath: '/marketing-prompts'
      preLoaderRoute: typeof MarketingPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-victoria': {
      id: '/meet-victoria'
      path: '/meet-victoria'
      fullPath: '/meet-victoria'
      preLoaderRoute: typeof MeetVictoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-center': {
      id: '/opportunity-center'
      path: '/opportunity-center'
      fullPath: '/opportunity-center'
      preLoaderRoute: typeof OpportunityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-templates': {
      id: '/pitch-templates'
      path: '/pitch-templates'
      fullPath: '/pitch-templates'
      preLoaderRoute: typeof PitchTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-developer-merchantid-domain-association': {
      id: '/.well-known/apple-developer-merchantid-domain-association'
      path: '/.well-known/apple-developer-merchantid-domain-association'
      fullPath: '/.well-known/apple-developer-merchantid-domain-association'
      preLoaderRoute: typeof Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-orders': {
      id: '/_authenticated/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompt-vault': {
      id: '/_authenticated/prompt-vault'
      path: '/prompt-vault'
      fullPath: '/prompt-vault'
      preLoaderRoute: typeof AuthenticatedPromptVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompt-vault-admin': {
      id: '/_authenticated/prompt-vault-admin'
      path: '/prompt-vault-admin'
      fullPath: '/prompt-vault-admin'
      preLoaderRoute: typeof AuthenticatedPromptVaultAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/thank-you': {
      id: '/services/thank-you'
      path: '/thank-you'
      fullPath: '/services/thank-you'
      preLoaderRoute: typeof ServicesThankYouRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPromptVaultRoute: typeof AuthenticatedPromptVaultRoute
  AuthenticatedPromptVaultAdminRoute: typeof AuthenticatedPromptVaultAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPromptVaultRoute: AuthenticatedPromptVaultRoute,
  AuthenticatedPromptVaultAdminRoute: AuthenticatedPromptVaultAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesThankYouRoute: typeof ServicesThankYouRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesThankYouRoute: ServicesThankYouRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatgptPromptsRoute: ChatgptPromptsRoute,
  FreePromptsRoute: FreePromptsRoute,
  GrantsAfricanWomenRoute: GrantsAfricanWomenRoute,
  GrantsForWomenRoute: GrantsForWomenRoute,
  JoinRoute: JoinRoute,
  MarketingPromptsRoute: MarketingPromptsRoute,
  McpRoute: McpRoute,
  MeetVictoriaRoute: MeetVictoriaRoute,
  MembershipRoute: MembershipRoute,
  OpportunityCenterRoute: OpportunityCenterRoute,
  PitchTemplatesRoute: PitchTemplatesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolkitRoute: ToolkitRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute:
    Char91DotwellKnownChar93AppleDeveloperMerchantidDomainAssociationRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
