CREATE TABLE public.side_hustles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  summary text NOT NULL,
  category text NOT NULL,
  level text NOT NULL,
  earning_potential text NOT NULL,
  startup_cost text NOT NULL,
  tools text[] NOT NULL DEFAULT '{}',
  first_steps text[] NOT NULL DEFAULT '{}',
  is_free_preview boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.side_hustles TO anon;
GRANT SELECT ON public.side_hustles TO authenticated;
GRANT ALL ON public.side_hustles TO service_role;

ALTER TABLE public.side_hustles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can browse the side hustle library"
ON public.side_hustles FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.member_side_hustles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  side_hustle_id uuid NOT NULL REFERENCES public.side_hustles(id) ON DELETE CASCADE,
  is_favorite boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'saved',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, side_hustle_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.member_side_hustles TO authenticated;
GRANT ALL ON public.member_side_hustles TO service_role;

ALTER TABLE public.member_side_hustles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members manage their own saved ideas"
ON public.member_side_hustles FOR ALL TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER member_side_hustles_set_updated_at
BEFORE UPDATE ON public.member_side_hustles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX side_hustles_category_idx ON public.side_hustles (category);
CREATE INDEX side_hustles_level_idx ON public.side_hustles (level);
CREATE INDEX member_side_hustles_user_idx ON public.member_side_hustles (user_id);

INSERT INTO public.side_hustles (slug, title, summary, category, level, earning_potential, startup_cost, tools, first_steps, is_free_preview) VALUES
('ai-notion-templates','AI-Built Notion Template Shop','Use AI to design and document premium Notion systems for founders, then sell them as instant downloads.','Digital Products','Beginner','$500–$4k/mo','Under $100','{ChatGPT,Notion,Canva,Gumroad}','{"Pick one audience and one painful workflow","Have Victoria draft the system structure and instructions","Design the cover art and sales page","List it and share a walkthrough reel"}',true),
('ai-caption-service','Done-For-You Caption Service','Write a month of on-brand social captions for small brands in a few hours using AI drafts you refine.','Content Creation','Beginner','$1k–$5k/mo','Under $100','{ChatGPT,Canva,"Google Docs"}','{"Choose three niches you understand","Build a voice questionnaire","Package 20 captions per month at a flat rate","Pitch 10 local businesses"}',true),
('ai-resume-writing','AI Résumé & LinkedIn Rewrites','Rewrite résumés and LinkedIn profiles for career changers with AI-assisted, ATS-friendly formatting.','Resume Writing','Beginner','$1k–$6k/mo','Under $100','{ChatGPT,Canva,"Google Docs"}','{"Create three résumé templates","Write an intake form for wins and metrics","Price a starter, standard and executive tier","Post before-and-after examples"}',true),
('faceless-youtube','Faceless YouTube Channel','Produce a niche faceless channel with AI scripts, AI voiceover and stock footage, monetised by ads and affiliates.','Content Creation','Intermediate','$500–$10k/mo','$100–$500','{ChatGPT,HeyGen,ElevenLabs,CapCut}','{"Pick a high-CPM niche","Script 10 videos in one sitting","Standardise thumbnails and titles","Publish twice weekly for 90 days"}',true),
('pod-quote-shop','Print-on-Demand Quote Brand','Sell AI-designed apparel and wall art around one specific identity or community.','Print-on-Demand','Beginner','$300–$3k/mo','Under $100','{Midjourney,Canva,Printify,Etsy}','{"Define one audience and its inside language","Generate 30 design concepts","Upload to a POD storefront","Test with organic short-form video"}',true),
('ai-social-management','Social Media Management Retainer','Run content calendars, captions and engagement for local service businesses with AI doing the heavy drafting.','Social Media Management','Intermediate','$2k–$10k/mo','Under $100','{ChatGPT,Canva,Later,Metricool}','{"Choose one industry to specialise in","Build a 30-day content framework","Offer a paid audit as the entry point","Convert audits into monthly retainers"}',false),
('ai-va-services','AI-Powered Virtual Assistant','Offer inbox, calendar and admin support supercharged by AI so you serve more clients per hour.','Virtual Assistant Services','Beginner','$1k–$5k/mo','Under $100','{ChatGPT,Notion,Zapier,"Google Workspace"}','{"List the 10 tasks you do fastest","Build AI templates for each","Package 10 or 20 hours monthly","Apply to three VA marketplaces"}',true),
('grant-writing-service','Grant Writing for Nonprofits','Draft compelling grant narratives with AI research and structure, charging per application or on retainer.','Grant Writing','Advanced','$3k–$15k/mo','Under $100','{ChatGPT,Grants.gov,"Google Docs"}','{"Study three funded proposals in your niche","Build a reusable narrative outline","Start with one small local nonprofit","Publish your win rate as proof"}',false),
('gov-contract-consulting','Government Contract Readiness Consulting','Help small businesses register, certify and bid for federal and state contracts.','Government Contracting','Advanced','$4k–$20k/mo','$100–$500','{SAM.gov,ChatGPT,"Google Sheets"}','{"Learn SAM.gov registration end to end","Map certifications to client profiles","Offer a readiness audit package","Build a capability statement template service"}',false),
('ai-course-creation','AI-Built Mini Course','Turn one skill you already have into a tight paid mini course, outlined and scripted with AI.','Education','Intermediate','$1k–$8k/mo','$100–$500','{ChatGPT,Canva,Loom,Teachable}','{"Pick one outcome students want fast","Outline five short modules","Record with slides and voiceover","Presell to your existing audience"}',true),
('ai-marketing-agency','Boutique AI Marketing Agency','Deliver campaign strategy, copy and creative for small brands with an AI-first production process.','Marketing Agencies','Advanced','$5k–$30k/mo','$500–$2k','{ChatGPT,Canva,"Meta Ads",Klaviyo}','{"Choose one offer and one industry","Document your AI production workflow","Land two case-study clients at a discount","Raise prices with proof in hand"}',false),
('ai-automation-consulting','AI Automation Consulting','Audit small-business workflows and build automations that save owners hours every week.','AI Automation','Advanced','$4k–$20k/mo','$100–$500','{Zapier,Make,ChatGPT,Airtable}','{"Learn one automation platform deeply","Offer a free 30-minute workflow audit","Quote by hours saved, not hours worked","Add a monthly maintenance retainer"}',false),
('ai-brand-kits','AI Brand Kit Studio','Produce logo suites, colour systems and brand guides fast using AI concepting plus your design taste.','Digital Products','Intermediate','$1k–$7k/mo','Under $100','{Midjourney,Canva,Figma}','{"Build three brand kit tiers","Create a 12-question brand questionnaire","Show three speculative brand kits","Offer a 5-day turnaround guarantee"}',false),
('email-newsletter','Paid Niche Newsletter','Build an audience with a sharp weekly newsletter drafted with AI and monetised by sponsors and paid tiers.','Content Creation','Intermediate','$500–$10k/mo','Under $100','{ChatGPT,Beehiiv,Canva}','{"Pick a niche you will still care about in a year","Commit to one send a week","Grow with short-form video and referrals","Open sponsorships at 1,000 subscribers"}',false),
('ai-etsy-printables','Etsy Printables Store','Sell AI-designed planners, worksheets and wall art as instant digital downloads.','E-commerce','Beginner','$300–$3k/mo','Under $100','{Canva,ChatGPT,Etsy}','{"Research low-competition keywords","Create 20 listings in one theme","Photograph styled mockups","Refresh listings monthly"}',true),
('ai-website-builds','AI-Assisted Website Builds','Build fast, beautiful sites for local businesses using AI copy and modern no-code tools.','Online Businesses','Intermediate','$2k–$12k/mo','$100–$500','{ChatGPT,Framer,Webflow,Canva}','{"Build one demo site per industry","Offer a fixed five-page package","Include copywriting as the differentiator","Add hosting and care plans"}',false),
('ai-podcast-production','Podcast Production Service','Edit, transcribe, clip and repurpose podcast episodes with AI tools on a monthly retainer.','Freelancing','Intermediate','$1.5k–$8k/mo','$100–$500','{Descript,ChatGPT,CapCut,Canva}','{"Master one AI editing tool","Package four episodes per month","Include five short clips per episode","Pitch shows with under 50 episodes"}',false),
('business-plan-service','Business Plan & Pitch Deck Service','Produce funder-ready business plans and decks with AI research and financial modelling support.','Consulting','Advanced','$3k–$15k/mo','Under $100','{ChatGPT,Canva,"Google Sheets"}','{"Build a master plan template","Create a financial model you reuse","Price by depth, not page count","Partner with lenders and incubators"}',false),
('ai-coaching-practice','AI-Supported Coaching Practice','Run a coaching practice where AI handles the plans, homework and recaps so you stay in the conversation.','Coaching','Intermediate','$2k–$15k/mo','Under $100','{ChatGPT,Notion,Calendly,Zoom}','{"Define one transformation you sell","Build a 12-week AI-assisted curriculum","Run a paid pilot with three clients","Collect outcomes and raise prices"}',false),
('affiliate-review-site','AI Tool Review Site','Build a review site for AI and software tools monetised through affiliate partnerships.','Affiliate Marketing','Intermediate','$500–$8k/mo','$100–$500','{ChatGPT,WordPress,Ahrefs,Canva}','{"Choose one software category","Publish 20 genuinely tested reviews","Apply to relevant affiliate programs","Build comparison pages for buyer keywords"}',false),
('ai-real-estate-marketing','Real Estate Listing Marketing','Provide agents with AI listing descriptions, reels, flyers and email follow-up.','Real Estate','Beginner','$1k–$6k/mo','Under $100','{ChatGPT,Canva,CapCut}','{"Build a listing intake form","Create a flyer and reel template pair","Charge per listing package","Pitch 20 agents with a sample"}',false),
('nonprofit-consulting','Nonprofit Startup Consulting','Guide founders through formation, board setup, storytelling and first funding using AI-drafted documents.','Nonprofit Consulting','Advanced','$3k–$12k/mo','$100–$500','{ChatGPT,Canva,"Google Docs"}','{"Learn your state formation process","Build a founding document bundle","Offer a 90-day launch program","Add grant readiness as an upsell"}',false),
('event-planning-ai','AI-Streamlined Event Planning','Plan events with AI handling timelines, vendor scripts, budgets and guest communications.','Event Planning','Intermediate','$2k–$12k/mo','$100–$500','{ChatGPT,Notion,Canva}','{"Choose one event type","Build a master timeline template","Create a vendor outreach script library","Package planning, styling and day-of tiers"}',false),
('beauty-brand-launch','Beauty Brand Launch','Launch a small beauty or fashion line with AI-driven branding, product copy and launch content.','Beauty & Fashion','Advanced','$1k–$20k/mo','$2k+','{Midjourney,Canva,Shopify,ChatGPT}','{"Validate one hero product","Source a compliant manufacturer","Build brand story and packaging copy","Run a waitlist launch"}',false),
('wellness-programs','Digital Wellness Programs','Sell structured wellness programs, meal guides or movement plans built with AI support.','Health & Wellness','Intermediate','$1k–$8k/mo','Under $100','{ChatGPT,Canva,Kajabi}','{"Pick one measurable result","Build a four-week program","Add accountability check-ins","Sell through short-form video"}',false),
('bookkeeping-ai','AI-Assisted Bookkeeping','Offer monthly bookkeeping and reporting for small businesses with AI categorisation and summaries.','Finance','Intermediate','$2k–$10k/mo','$100–$500','{QuickBooks,ChatGPT,"Google Sheets"}','{"Get certified on one accounting platform","Standardise a monthly close checklist","Price per transaction volume","Add a plain-English monthly report"}',false),
('ai-chatbot-builds','Custom AI Chatbot Builds','Build trained support and sales chatbots for small businesses, charging setup plus monthly hosting.','Technology','Advanced','$3k–$20k/mo','$100–$500','{ChatGPT,"Vector databases",Zapier}','{"Build one demo bot for a real business","Document your training process","Charge setup plus a monthly fee","Target businesses with repetitive questions"}',false),
('business-credit-consulting','Business Credit Consulting','Guide founders through entity setup, tradelines and lender readiness with AI-organised action plans.','Finance','Advanced','$3k–$15k/mo','$100–$500','{ChatGPT,"Google Sheets",Notion}','{"Master the funding readiness checklist","Build a 90-day credit roadmap","Offer an audit as the front end","Track and publish client outcomes"}',false),
('ai-video-ads','AI Video Ad Studio','Produce short-form video ads for brands using AI avatars, scripts and generated b-roll.','Content Creation','Intermediate','$2k–$12k/mo','$100–$500','{HeyGen,Kling,CapCut,ChatGPT}','{"Build a five-ad spec portfolio","Standardise a hook-body-CTA script formula","Sell packs of six ads","Offer performance-based reorders"}',false),
('digital-planner-shop','Digital Planner Studio','Design hyperlinked digital planners for tablets, generated and refined with AI.','Digital Products','Beginner','$300–$4k/mo','Under $100','{Canva,ChatGPT,GoodNotes,Etsy}','{"Choose one planning method","Build one flagship planner","Record a setup tutorial","Bundle seasonal add-ons"}',false),
('ai-seo-service','AI-Powered SEO Content Service','Deliver keyword-researched, human-edited content programs for small brands.','Freelancing','Intermediate','$2k–$10k/mo','$100–$500','{ChatGPT,Ahrefs,"Google Search Console"}','{"Learn keyword clustering","Package four articles per month","Report on rankings monthly","Start with one industry"}',false),
('ai-prompt-packs','Prompt Pack Publishing','Package tested prompt libraries for specific professions and sell them as digital products.','Digital Products','Beginner','$300–$3k/mo','Under $100','{ChatGPT,Notion,Canva,Gumroad}','{"Pick a profession you know","Test 50 prompts on real tasks","Document inputs and outputs","Sell with a free 5-prompt sample"}',true),
('ai-customer-service','Outsourced Customer Support','Provide AI-assisted email and chat support for e-commerce brands.','Online Businesses','Intermediate','$2k–$10k/mo','Under $100','{ChatGPT,Gorgias,Zendesk}','{"Build a macro and tone library","Guarantee a response-time SLA","Price per ticket volume","Start with one Shopify brand"}',false),
('interior-design-ai','AI Interior Design Boards','Sell room design concepts, mood boards and shoppable product lists created with AI renders.','Beauty & Fashion','Beginner','$800–$5k/mo','Under $100','{Midjourney,Canva,Pinterest}','{"Build three style board samples","Create an intake form with photos","Offer a fixed per-room price","Grow with before-and-after reels"}',false),
('ai-newsletter-agency','Newsletter Agency for Coaches','Write and send weekly newsletters for busy coaches and consultants.','Marketing Agencies','Intermediate','$2k–$10k/mo','Under $100','{ChatGPT,Beehiiv,Klaviyo}','{"Build a voice-capture interview","Package four sends per month","Report opens and clicks monthly","Pitch coaches with big audiences and no list"}',false),
('ai-tutoring','AI-Enhanced Tutoring','Tutor students with AI-generated practice sets, explanations and progress summaries for parents.','Education','Beginner','$1k–$5k/mo','Under $100','{ChatGPT,Zoom,"Google Docs"}','{"Choose one subject and grade band","Build a diagnostic assessment","Sell 8-session packages","Send AI-written parent progress reports"}',false),
('ai-ugc-creator','UGC Creator for Brands','Create user-generated-style content for brands, scripted and optimised with AI.','Content Creation','Beginner','$1k–$8k/mo','Under $100','{ChatGPT,CapCut,"Ring light"}','{"Film three spec UGC videos","Build a simple rate card","Pitch 20 DTC brands weekly","Offer usage rights as an upsell"}',false),
('ai-legal-templates','Small Business Template Shop','Sell contracts, SOPs and policy templates drafted with AI and reviewed for your niche.','Digital Products','Intermediate','$500–$5k/mo','$100–$500','{ChatGPT,"Google Docs",Gumroad}','{"Choose one industry","Draft a five-document starter bundle","Have a professional review the pack","Sell as a bundle with a usage guide"}',false),
('ai-recruiting','Niche Recruiting Service','Source and screen candidates for a specific role type using AI-assisted outreach and screening.','Consulting','Advanced','$4k–$20k/mo','$100–$500','{ChatGPT,LinkedIn,Airtable}','{"Pick one role you understand","Build a scorecard and screening script","Charge a placement fee","Build a warm candidate pool"}',false),
('remote-job-coaching','Remote Career Coaching','Coach clients into remote roles with AI-built résumés, interview prep and application systems.','Coaching','Intermediate','$2k–$10k/mo','Under $100','{ChatGPT,Notion,Zoom}','{"Map a 60-day job search sprint","Build an AI interview prep drill","Sell a coaching package, not hours","Publish client placement stories"}',false),
('ai-translation','AI-Assisted Localisation','Localise marketing content between languages with AI drafts and your native-speaker polish.','Freelancing','Intermediate','$1.5k–$8k/mo','Under $100','{ChatGPT,DeepL,"Google Docs"}','{"Choose one language pair and niche","Build a glossary per client","Price per thousand words","Pitch brands expanding internationally"}',false),
('membership-community','Paid Membership Community','Run a paid community with AI-prepped weekly prompts, resources and coaching content.','Online Businesses','Advanced','$2k–$20k/mo','$100–$500','{ChatGPT,Circle,Kajabi,Canva}','{"Define one clear member outcome","Plan a repeatable monthly rhythm","Launch with a founding-member cohort","Add annual pricing"}',false),
('ai-photo-editing','AI Product Photo Studio','Turn plain product photos into scroll-stopping lifestyle imagery with AI editing.','E-commerce','Beginner','$800–$5k/mo','Under $100','{Photoshop,Midjourney,Canva}','{"Build a 10-image before-and-after portfolio","Offer packs of 20 images","Guarantee 48-hour turnaround","Pitch small Shopify and Etsy sellers"}',false),
('ai-sales-scripts','Sales Script & Funnel Consulting','Build objection-handling scripts, follow-up sequences and funnels using AI plus real call data.','Consulting','Advanced','$3k–$15k/mo','Under $100','{ChatGPT,Notion,Loom}','{"Listen to real sales calls","Build a script and objection library","Sell a 30-day funnel sprint","Charge for measurable lift"}',false),
('ai-voiceover','AI Voiceover & Audio Service','Produce narration, ads and audiobooks using AI voices you direct and master.','Technology','Beginner','$800–$6k/mo','$100–$500','{ElevenLabs,Descript,Audacity}','{"Build a three-style demo reel","Learn licensing and disclosure rules","Price per finished minute","List on freelance marketplaces"}',false),
('ai-bookkeeping-templates','Finance Template Publishing','Sell budget, forecast and pricing calculators built for small service businesses.','Finance','Beginner','$300–$3k/mo','Under $100','{"Google Sheets",ChatGPT,Gumroad}','{"Build one calculator you would use","Record a two-minute walkthrough","Bundle three related tools","Sell to your existing audience first"}',false),
('ai-personal-branding','Personal Brand Management','Manage founders'' personal brands end to end: content, engagement and thought leadership with AI drafting.','Social Media Management','Advanced','$3k–$15k/mo','Under $100','{ChatGPT,LinkedIn,Canva,Metricool}','{"Choose one platform to own","Build a five-pillar content system","Offer a 90-day visibility sprint","Report reach and inbound leads"}',false),
('ai-workshop-facilitation','AI Workshop Facilitation','Teach paid workshops showing teams and organisations how to actually use AI in their work.','Education','Advanced','$3k–$20k/mo','$100–$500','{ChatGPT,Canva,Zoom,Notion}','{"Build one 90-minute flagship workshop","Create a takeaway prompt workbook","Price per session plus per seat","Pitch chambers, nonprofits and agencies"}',false);