CREATE TEMP TABLE prompt_specs (
  ord serial,
  category text,
  title text,
  description text,
  goal text,
  deliverables text[]
);

INSERT INTO prompt_specs (category, title, description, goal, deliverables) VALUES
('marketing','Build My Marketing Strategy','Creates a complete, practical marketing strategy you can run for the next 90 days.','Design a focused marketing strategy for my business that fits my time, budget and audience.',ARRAY['A one-paragraph positioning statement in plain language','My three best marketing channels with the reason each one fits my audience','A 90-day plan broken into monthly themes and weekly actions','Three measurable targets and how to track them each week']),
('marketing','Identify My Ideal Target Audience','Defines exactly who you serve so every message lands with the right woman.','Define my ideal customer in detail so I stop marketing to everyone.',ARRAY['Two detailed audience segments with demographics, goals and daily frustrations','The exact words each segment uses to describe her problem','Where each segment spends time online and offline','Three message angles per segment, ranked by likely response']),
('marketing','Write My Unique Value Proposition','Turns what makes you different into one clear, confident sentence.','Write a unique value proposition that makes my business the obvious choice.',ARRAY['Five value proposition options in different tones','The strongest option with an explanation of why it wins','A short and long version for my website and social bios','Three proof points that back the claim up']),
('marketing','Plan My Product Launch','Maps a full launch from announcement to sales close.','Plan a launch for my new offer that builds anticipation and converts.',ARRAY['A four-week launch timeline with daily tasks','Messaging for each launch phase: tease, teach, open, close','An email and social post outline for every phase','A simple revenue target with the number of sales needed']),
('marketing','Create My Customer Profile','Builds a rich profile of the buyer who says yes fastest.','Create a detailed customer profile I can use for all my marketing decisions.',ARRAY['A named profile with background, budget and buying triggers','Her objections and the exact reassurance that answers each one','Her buying journey from first hearing about me to purchase','Five content ideas written specifically for her']),
('marketing','Develop My Brand Voice','Gives you a written voice guide so everything you publish sounds like you.','Define a brand voice that feels elegant, warm and unmistakably mine.',ARRAY['Three voice traits with a short definition of each','Words and phrases to use and to avoid','Before-and-after examples of the same sentence in my voice','A short reusable voice checklist']),
('marketing','Write Promotional Copy That Converts','Produces persuasive copy for an offer without sounding pushy.','Write promotional copy for my offer that is warm, clear and persuasive.',ARRAY['Three headline options and three opening lines','A short-form version for social and a long-form version for email','A benefits section written as outcomes, not features','Two closing calls to action with different levels of urgency']),
('marketing','Build My Monthly Marketing Calendar','Lays out a full month of marketing so you never start from a blank page.','Create a marketing calendar for the coming month across all my channels.',ARRAY['A week-by-week theme for the month','A dated table of posts, emails and offers','The one priority action for each week','A light version of the plan for a busy week']),
('social-media','Create My 30-Day Content Calendar','Gives you a month of ready content ideas mapped day by day.','Build a 30-day social media content calendar for my business.',ARRAY['A dated 30-day table with theme, format and hook for each day','A balanced mix of educational, personal, proof and selling posts','Three recurring series I can repeat every month','Two backup posts for low-energy days']),
('social-media','Write Instagram Captions That Sell','Writes captions with strong hooks and a natural call to action.','Write Instagram captions for my business that stop the scroll and invite action.',ARRAY['Five captions in different styles: story, tip, proof, behind the scenes, offer','A strong first line for each caption','A relevant call to action for each caption','Fifteen hashtags grouped by reach level']),
('social-media','Create Professional LinkedIn Posts','Positions you as the credible expert in your field.','Write LinkedIn posts that build my professional authority and attract clients.',ARRAY['Three posts: an insight, a client result and a lesson learned','A scroll-stopping first two lines for each post','Clean formatting with short lines and spacing','A closing question to invite comments']),
('social-media','Write Facebook Promotional Posts','Creates warm, community-friendly posts that promote without pressure.','Write Facebook posts that promote my offer to a warm community audience.',ARRAY['Three posts with different angles on the same offer','A conversational opening for each post','A clear link call to action for each post','A short version for a Facebook group where self-promotion is limited']),
('social-media','Generate Short-Form Video Ideas','Produces a batch of video concepts built for reels, TikTok and shorts.','Give me short-form video ideas that suit my business and are easy to film.',ARRAY['Fifteen video concepts with a hook line for each','The format and rough length for each idea','Which ideas are best for reach and which are best for sales','A simple filming order so I can batch them']),
('social-media','Write A Short Video Script','Turns one idea into a tight, filmable script.','Write a short video script for my business that holds attention to the end.',ARRAY['A three-second hook and a reason to keep watching','A word-for-word script under sixty seconds','On-screen text and shot suggestions','Two alternative endings: one soft, one direct']),
('social-media','Write Calls To Action That Work','Gives you natural ways to ask for the next step.','Write calls to action for my content that feel confident, not pushy.',ARRAY['Ten calls to action grouped by goal: save, comment, click, buy','A soft and a direct version of each key ask','Wording for a first-time viewer and for a warm follower','Guidance on when to use each one']),
('social-media','Repurpose One Idea Across Platforms','Stretches a single idea into a full week of content.','Turn one idea into content for every platform I use.',ARRAY['A core message summarised in one sentence','Versions for Instagram, LinkedIn, Facebook, short video and email','A blog or newsletter outline built from the same idea','A posting order across the week']),
('grants-funding','Find Grant Opportunities That Fit','Helps you search smartly for funding that matches your business.','Help me identify the types of grant opportunities that may fit my business.',ARRAY['The funding categories most relevant to my business type','Search terms, databases and organisations to look through','What each funder type usually expects from applicants','A shortlist template for tracking opportunities and deadlines']),
('grants-funding','Create My Grant-Readiness Checklist','Shows exactly which documents and details to prepare before applying.','Create a grant-readiness checklist so my business is prepared to apply.',ARRAY['A checklist of documents, registrations and records commonly requested','What is usually needed for my business stage','Gaps to close first, ordered by importance','A simple filing structure so documents are easy to find']),
('grants-funding','Write My Organization Description','Drafts a clear, credible description of your business or organisation.','Write a professional organisation description for grant applications.',ARRAY['A 150-word and a 300-word version','A history and mission paragraph in plain, confident language','A paragraph on who we serve and how','A short list of strengths and credentials to include']),
('grants-funding','Draft My Statement Of Need','Helps you explain the problem your work addresses with clarity and evidence.','Draft a statement of need for my funding application.',ARRAY['A clear problem statement in one paragraph','Supporting points and the kinds of data to cite','Why my business is well placed to respond','A version tightened to a strict word limit']),
('grants-funding','Explain My Community Impact','Puts your community contribution into language funders understand.','Describe the community impact of my work for a funding application.',ARRAY['A description of who benefits and how','Short-term and long-term impact written separately','Two brief anonymised story examples I can adapt','Ways to describe impact when formal data is limited']),
('grants-funding','Outline My Project Budget','Structures a clear, defensible budget for your project.','Create a project budget outline for a funding request.',ARRAY['A budget table with categories and example line items','A one-line justification for each category','Guidance on separating direct and administrative costs','A short budget narrative to accompany the table']),
('grants-funding','Write Measurable Goals And Outcomes','Turns intentions into goals a funder can evaluate.','Write measurable goals and outcomes for my funded project.',ARRAY['Three goals written in measurable terms','Outputs and outcomes separated clearly for each goal','How each result will be tracked and reported','A simple evaluation timeline']),
('grants-funding','Prepare Questions For A Funder','Gets you ready for a call or meeting with a funding officer.','Prepare thoughtful questions and answers for a conversation with a funder.',ARRAY['Ten questions to ask that show preparation','Answers to the questions a funder is likely to ask me','A two-minute spoken summary of my project','A short follow-up note to send afterwards']),
('business-planning','Create My Business Plan Outline','Gives you a complete, practical business plan structure to fill in.','Create a business plan outline tailored to my business.',ARRAY['A full section-by-section outline with what each section must answer','Prompts and example wording for each section','A one-page summary version','The order to complete the sections in']),
('business-planning','Develop My Mission And Vision','Writes mission and vision statements that guide real decisions.','Write a mission and vision statement for my business.',ARRAY['Three mission options and three vision options','The strongest pair with an explanation','A short version for my website and a longer internal version','Three values with a sentence describing each in practice']),
('business-planning','Run A SWOT Analysis','Reveals your strengths, gaps, openings and risks in one clear view.','Run a SWOT analysis on my business and tell me what to do about it.',ARRAY['A SWOT table with specific, honest points','The two strengths to lean on hardest','The two weaknesses to fix first and how','Three actions drawn from the opportunities and threats']),
('business-planning','Set My Revenue Goals','Turns a revenue wish into a plan with real numbers.','Set realistic revenue goals for my business and show me the maths.',ARRAY['An annual, quarterly and monthly revenue target','The number of sales needed at my price points','Assumptions listed openly so I can adjust them','Three levers to raise revenue without more hours']),
('business-planning','Build My Pricing Strategy','Helps you price by value with confidence.','Build a pricing strategy for my offers that reflects their value.',ARRAY['A recommended price range with the reasoning','A three-tier offer structure with what belongs in each tier','Payment plan and bundle options','Wording to explain a price increase to existing clients']),
('business-planning','Research My Competitors','Shows where you stand and where the open space is.','Analyse my competitors and show me how to stand apart.',ARRAY['A comparison table of likely competitor types and their positioning','What they do well and where they leave gaps','Three ways I can differentiate credibly','Two positioning statements built from those gaps']),
('business-planning','Plan A New Service','Takes a service idea from concept to launch-ready.','Help me design and plan a new service for my business.',ARRAY['The service described in client-facing language','What is included, excluded and how delivery works','Pricing, timeline and the tools I need','A launch checklist with the first five steps']),
('business-planning','Create My 90-Day Action Plan','Gives you a focused quarter with weekly priorities.','Create a 90-day action plan that moves my business forward.',ARRAY['One primary goal for the quarter','Monthly milestones and weekly priority actions','A short weekly review routine','What to say no to for the next 90 days']),
('professional-emails','Introduce My Business By Email','Writes a warm, professional introduction email that gets replies.','Write an email introducing my business to a new contact or organisation.',ARRAY['Three subject line options','A short version and a detailed version of the email','A credibility line and a clear, low-pressure ask','A polite follow-up email to send a week later']),
('professional-emails','Follow Up With A Potential Client','Keeps a warm lead moving without pressure.','Write a follow-up email to a potential client who has not replied yet.',ARRAY['Three follow-ups spaced over two weeks, each with a new reason to reply','Subject lines for each message','A gentle final message that leaves the door open','Wording to use if she says the timing is wrong']),
('professional-emails','Respond To A Customer Complaint','Handles a difficult message with grace and keeps the relationship.','Write a professional reply to a customer complaint.',ARRAY['A calm reply that acknowledges the concern','A clear explanation and the resolution offered','Two versions: one where I made the error, one where I did not','A short internal note on preventing a repeat']),
('professional-emails','Request A Meeting','Asks for someone''s time in a way that is easy to say yes to.','Write an email requesting a meeting with a client, partner or funder.',ARRAY['A concise request with a clear purpose and length','Two or three suggested time options','A version for a warm contact and one for a cold contact','A short agenda to attach']),
('professional-emails','Write A Partnership Proposal Email','Presents a collaboration that benefits both sides.','Write an email proposing a partnership or collaboration.',ARRAY['An opening that shows genuine knowledge of their work','The proposed collaboration in three sentences','What each side contributes and gains','A simple next step and a professional close']),
('professional-emails','Send An Invoice Reminder','Chases payment politely and firmly.','Write an invoice reminder email that protects the relationship and gets me paid.',ARRAY['A friendly first reminder','A firmer second reminder with the payment terms restated','A final notice that remains professional','A short payment policy line for future invoices']),
('professional-emails','Thank A Customer','Turns appreciation into repeat business and referrals.','Write a thank-you email to a customer after a purchase or project.',ARRAY['A warm thank-you email that is specific, not generic','A natural invitation to leave a review or refer a friend','A version for a first-time buyer and for a long-term client','A short handwritten-note version']),
('professional-emails','Reconnect With A Professional Contact','Restarts a valuable relationship after months of silence.','Write an email reconnecting with a contact I have not spoken to in a while.',ARRAY['An honest, unawkward opening about the gap in contact','A short update on my business','A generous offer before any ask','A clear, small next step']),
('resumes-career','Improve My Resume Summary','Rewrites your professional summary so it opens strong.','Rewrite my resume summary so it is confident and specific.',ARRAY['Three summary options of three to four lines each','Strong opening descriptors instead of tired phrases','A version aimed at a specific role and an all-purpose version','A note on what to cut from my current summary']),
('resumes-career','Turn Duties Into Accomplishments','Rewrites job tasks as results that impress.','Rewrite my job duties as achievement statements with measurable results.',ARRAY['Each duty rewritten as an achievement with action, method and result','Suggested metrics I could add and how to estimate them honestly','Stronger action verbs grouped by skill type','The top five bullets to lead with']),
('resumes-career','Tailor My Resume To A Job','Aligns your resume to the exact role you want.','Tailor my resume to a specific job description.',ARRAY['The key requirements pulled out of the job description','Which of my experiences match each requirement','Rewritten bullets using the language of the posting','Honest ways to address any gaps']),
('resumes-career','Write My Cover Letter','Produces a cover letter that sounds like a person, not a template.','Write a cover letter for a role I am applying for.',ARRAY['A one-page letter with a memorable opening','A middle section connecting my experience to their needs','A closing that states my interest clearly','A shorter version for an online application box']),
('resumes-career','Prepare Me For The Interview','Gets you ready with answers, stories and questions.','Prepare me for an interview for a role I want.',ARRAY['Twelve likely questions with strong sample answers','Three achievement stories in situation-action-result form','Six thoughtful questions to ask them','How to answer salary and weakness questions calmly']),
('resumes-career','Write My Professional Biography','Creates a polished bio for websites, panels and press.','Write a professional biography for my website and speaking profiles.',ARRAY['A short bio of about 75 words','A medium bio of about 150 words','A long bio of about 300 words','First-person and third-person versions']),
('resumes-career','Write My LinkedIn Summary','Makes your profile read like the professional you are.','Write a LinkedIn About section that attracts the right opportunities.',ARRAY['A first-person About section with a strong hook','A middle section on expertise and results','A closing line inviting the right people to reach out','Five headline options and relevant keywords to include']),
('resumes-career','Write A Post-Interview Thank You','Sends the note that keeps you memorable.','Write a thank-you email to send after an interview.',ARRAY['A short thank-you email sent within a day','A reference to something specific from the conversation','One sentence that reinforces my strongest fit','A polite status-check message for a week later']),
('productivity','Create My Weekly Schedule','Builds a realistic week that protects your energy and your revenue work.','Create a weekly schedule for me that fits my business and my life.',ARRAY['A day-by-day schedule with time blocks','Protected blocks for revenue work, admin and rest','Where to place similar tasks together','A lighter version for an unpredictable week']),
('productivity','Prioritise My Task List','Sorts a long, overwhelming list into a clear order.','Take my task list and tell me what to do first and what to drop.',ARRAY['My tasks sorted into do now, schedule, delegate and delete','The three tasks with the highest business impact','A realistic plan for today and tomorrow','What can wait without consequence']),
('productivity','Build My Daily Routine','Designs a morning-to-evening rhythm that keeps you consistent.','Design a daily routine that supports my business and my wellbeing.',ARRAY['A morning, working and evening routine','A ninety-minute deep-work block and where it fits','A short shutdown routine to end the day cleanly','A minimum version for hard days']),
('productivity','Break Down A Big Goal','Turns an intimidating goal into small, doable steps.','Break my big goal into clear steps I can actually start.',ARRAY['The goal broken into phases with milestones','Every phase reduced to tasks under an hour where possible','The first three steps to take this week','Likely obstacles and a plan for each']),
('productivity','Write A Standard Operating Procedure','Documents a task so it can be repeated or handed over.','Write a standard operating procedure for a task in my business.',ARRAY['A titled procedure with purpose, owner and frequency','Numbered steps written so a new person could follow them','Tools, links and templates needed','A quality checklist and common mistakes to avoid']),
('productivity','Plan A Productive Work Week','Sets up the week ahead with focus and realistic expectations.','Plan my most productive work week around my current priorities.',ARRAY['One clear focus for the week','Daily themes so similar work stays together','A Monday setup and Friday review routine','Two things to postpone to protect the focus']),
('productivity','Automate Repetitive Business Tasks','Finds the work you should stop doing by hand.','Show me which repetitive tasks in my business I can automate or simplify.',ARRAY['My repetitive tasks grouped by type','Which to automate, which to template and which to delegate','Simple, low-cost tools that could handle each one','A step-by-step setup plan for the top three']),
('productivity','Create My 30-Day Action Plan','Gives you a focused month with daily momentum.','Create a 30-day action plan to reach one specific business goal.',ARRAY['One measurable goal for the 30 days','Weekly milestones and daily actions','A short tracking method I will actually keep up','A recovery plan for the days I fall behind']);

INSERT INTO public.prompts (slug, title, category, description, body, sort_order, is_featured, is_published)
SELECT
  regexp_replace(lower(s.title), '[^a-z0-9]+', '-', 'g') || '-' || s.category,
  s.title,
  s.category,
  s.description,
  'You are a senior ' ||
    CASE s.category
      WHEN 'marketing' THEN 'marketing strategist'
      WHEN 'social-media' THEN 'social media strategist and copywriter'
      WHEN 'grants-funding' THEN 'grant writer and funding consultant'
      WHEN 'business-planning' THEN 'business planning consultant'
      WHEN 'professional-emails' THEN 'business communication specialist'
      WHEN 'resumes-career' THEN 'career coach and professional resume writer'
      ELSE 'productivity and operations consultant'
    END ||
  ' working with the founder of [BUSINESS NAME], a [INDUSTRY] business serving [TARGET AUDIENCE].' || E'\n\n' ||
  'GOAL' || E'\n' || s.goal || E'\n\n' ||
  'MY DETAILS' || E'\n' ||
  '- Business name: [BUSINESS NAME]' || E'\n' ||
  '- Industry: [INDUSTRY]' || E'\n' ||
  '- Target audience: [TARGET AUDIENCE]' || E'\n' ||
  '- Main offer: [PRODUCT]' || E'\n' ||
  '- What I want most right now: [GOAL]' || E'\n\n' ||
  'WHAT TO PRODUCE' || E'\n' ||
  (SELECT string_agg('- ' || d, E'\n') FROM unnest(s.deliverables) AS d) || E'\n\n' ||
  'HOW TO WORK' || E'\n' ||
  '1. Do not ask me questions before you begin. Make sensible assumptions and label them clearly at the end.' || E'\n' ||
  '2. Write in a warm, confident, professional voice suited to a woman-owned business.' || E'\n' ||
  '3. Be specific and usable: real numbers, examples and wording I can act on today, never vague filler.' || E'\n' ||
  '4. Use clear headings, short paragraphs, and tables or numbered lists where they make the work easier to follow.' || E'\n' ||
  '5. Finish with a "Next 3 actions" list and one question that would make the result even stronger.' ||
  CASE WHEN s.category = 'grants-funding'
    THEN E'\n\n' || 'NOTE: This prompt offers educational and writing assistance only. It does not guarantee funding or grant approval.'
    ELSE '' END,
  s.ord,
  s.ord % 8 = 1,
  true
FROM prompt_specs s;

DROP TABLE prompt_specs;