
DELETE FROM public.prompt_favorites;
DELETE FROM public.prompt_usage;
DELETE FROM public.prompts;

INSERT INTO public.prompts (slug, title, category, description, body, sort_order, is_featured) VALUES
-- Marketing
('brand-identity-blueprint','Brand Identity Blueprint','Marketing','Define your brand voice, visual identity, and positioning in one document.','Act as a brand strategist. Build a complete brand identity blueprint for {{business_name}}, which sells {{product_service}} to {{target_audience}}. Include: brand promise, positioning statement, 3 brand values, tone-of-voice rules with do/do-not examples, colour and typography direction, and 5 messaging pillars. Keep the tone {{brand_tone}}.',1,true),
('30-day-marketing-calendar','30-Day Marketing Calendar','Marketing','Generate a full month of marketing activity mapped to your goals.','Act as a marketing director. Create a 30-day marketing calendar for {{business_name}} with the goal of {{primary_goal}}. Our channels are {{channels}} and our audience is {{target_audience}}. Give a table with day, channel, topic, format, call to action, and the metric to track. End with 3 ways to repurpose the best-performing content.',2,false),
('positioning-statement-generator','Positioning Statement Generator','Marketing','Craft a sharp, differentiated positioning statement.','Act as a positioning expert. Write 5 positioning statement options for {{business_name}}, which helps {{target_audience}} achieve {{main_outcome}} through {{product_service}}. Our main competitors are {{competitors}}. For each option, explain the differentiator and who it will attract. Then recommend the strongest one and why.',3,false),
('offer-launch-plan','Offer Launch Plan','Marketing','Plan a full launch from teaser to close.','Act as a launch strategist. Build a launch plan for {{offer_name}}, priced at {{price}}, for {{target_audience}}. The launch window is {{timeframe}}. Include: pre-launch warm-up, launch week content plan, objection-handling messages, urgency mechanics, email and social touchpoints, and a simple revenue goal breakdown.',4,false),
('ideal-client-profile','Ideal Client Profile','Marketing','Build a detailed profile of the client you most want to attract.','Act as a market researcher. Build a detailed ideal client profile for {{business_name}}, which offers {{product_service}}. Include: demographics, daily life, top 3 pains, top 3 desires, buying triggers, objections, where they spend time online, and the exact language they use to describe their problem.',5,false),
('website-homepage-copy','Website Homepage Copy','Marketing','Write conversion-focused homepage copy section by section.','Act as a conversion copywriter. Write homepage copy for {{business_name}}, which sells {{product_service}} to {{target_audience}}. Deliver: hero headline plus subheadline, 3 benefit blocks, social proof section, how-it-works in 3 steps, FAQ with 5 questions, and a closing call to action. Tone: {{brand_tone}}.',6,false),
('marketing-funnel-audit','Marketing Funnel Audit','Marketing','Find the leaks between attention and purchase.','Act as a growth consultant. Audit the marketing funnel for {{business_name}}. Here is what happens today: {{current_funnel}}. Our conversion problem is {{main_problem}}. Identify the likely leak at each stage (awareness, interest, consideration, purchase, retention), rank fixes by impact versus effort, and give a 2-week action list.',7,false),
('press-release-writer','Press Release Writer','Marketing','Announce news in a format journalists will actually use.','Act as a PR specialist. Write a press release for {{business_name}} announcing {{announcement}}. Audience: {{target_audience}}. Include headline, subheadline, dateline, lead paragraph answering who/what/when/where/why, two quotes, boilerplate, and media contact placeholder. Keep it under 500 words and factual.',8,false),
-- Social Media
('instagram-reel-hooks','Instagram Reel Hooks','Social Media','Get 20 scroll-stopping hooks for your next reels.','Act as a short-form video strategist. Write 20 hooks for Instagram Reels for {{business_name}} on the topic of {{topic}} for {{target_audience}}. Mix curiosity, contrarian, mistake-based, listicle, and story hooks. Keep each under 12 words and note which emotion it triggers.',1,true),
('7-day-caption-pack','7-Day Caption Pack','Social Media','A week of ready-to-post captions in your voice.','Act as a social media copywriter. Write 7 Instagram captions for {{business_name}} about {{topic}}, aimed at {{target_audience}}. Vary the format: story, tip list, myth-buster, behind the scenes, testimonial framing, question post, and offer post. Each caption needs a hook line, body, and call to action. Tone: {{brand_tone}}.',2,false),
('content-pillar-planner','Content Pillar Planner','Social Media','Turn your expertise into repeatable content pillars.','Act as a content strategist. Create 5 content pillars for {{business_name}}, which helps {{target_audience}} with {{main_outcome}}. For each pillar give: purpose, 6 content ideas, best format, and posting frequency. Finish with a weekly posting schedule across {{channels}}.',3,false),
('carousel-script-builder','Carousel Script Builder','Social Media','Write a 10-slide carousel that saves and shares well.','Act as a carousel designer and copywriter. Write a 10-slide Instagram or LinkedIn carousel for {{business_name}} on {{topic}} for {{target_audience}}. Slide 1 is the hook, slides 2-9 deliver one idea each with short text, slide 10 is the call to action. Add a design note for each slide.',4,false),
('tiktok-video-script','TikTok Video Script','Social Media','A 30-second script with hook, value, and call to action.','Act as a TikTok creator strategist. Write a 30-second video script for {{business_name}} about {{topic}} for {{target_audience}}. Format it as a table with timestamp, spoken line, on-screen text, and visual direction. Include 3 alternate hooks and a caption with 5 relevant hashtags.',5,false),
('linkedin-authority-post','LinkedIn Authority Post','Social Media','Position yourself as the expert in your niche.','Act as a LinkedIn ghostwriter. Write a thought-leadership post for {{author_name}}, who helps {{target_audience}} with {{main_outcome}}. The point of view is {{key_message}}. Use short lines, a strong first line, one story or data point, a practical takeaway list, and a question to invite comments. No hashtags in the body.',6,false),
('hashtag-and-seo-kit','Hashtag & Search Kit','Social Media','Get discovered with keywords and hashtags that fit your niche.','Act as a social SEO specialist. For {{business_name}} in the {{industry}} space targeting {{target_audience}}, produce: 10 broad hashtags, 10 niche hashtags, 10 community hashtags, 15 searchable keywords to say out loud in video, and 5 profile bio keyword suggestions. Explain how to rotate them.',7,false),
('comment-reply-scripts','Comment & DM Reply Scripts','Social Media','Reply fast without losing your brand voice.','Act as a community manager. Write reply scripts for {{business_name}} in a {{brand_tone}} tone. Cover: compliment, pricing question, "does this work for me" question, objection, negative comment, spam, and a warm DM that moves someone toward {{product_service}} without hard selling. Give 2 variations each.',8,false),
-- Grants & Funding
('grant-opportunity-research','Grant Opportunity Research','Grants & Funding','Build a shortlist of funding sources worth your time.','Act as a grant research assistant. Educational use only. Help me build a research plan to find funding for {{business_name}}, a {{business_type}} based in {{location}} seeking approximately {{funding_amount}} for {{funding_purpose}}. List categories of funders to explore, search terms, eligibility questions to verify, and a tracking table with funder, deadline, amount, fit score, and requirements. Note clearly that all details must be verified directly with each funder.',1,true),
('grant-narrative-draft','Grant Narrative Draft','Grants & Funding','Draft a clear need, solution, and impact narrative.','Act as a grant writer. Educational use only. Draft a grant narrative for {{business_name}} requesting {{funding_amount}} for {{funding_purpose}}. Community or audience served: {{target_audience}}. Include: statement of need, project description, goals and measurable objectives, implementation timeline, evaluation plan, and sustainability. Mark every place where I must insert verified data or citations.',2,false),
('grant-budget-justification','Grant Budget Justification','Grants & Funding','Explain every line item in language funders expect.','Act as a grant budget specialist. Educational use only. Build a budget justification for a {{funding_amount}} request by {{business_name}} for {{funding_purpose}}. My planned costs are {{cost_items}}. For each line, write the amount, calculation method, and a one-paragraph justification tied to project outcomes. Flag any cost commonly considered unallowable so I can verify with the funder.',3,false),
('letter-of-inquiry','Letter of Inquiry','Grants & Funding','A one-page introduction that opens the door.','Act as a grant writer. Educational use only. Write a one-page letter of inquiry from {{business_name}} to {{funder_name}} requesting {{funding_amount}} for {{funding_purpose}}. Include a hook, organisation credibility, the need, the proposed project, the ask, and a polite next step. Keep it under 500 words and note where to add verified outcomes data.',4,false),
('program-impact-statement','Program Impact Statement','Grants & Funding','Show measurable outcomes, not good intentions.','Act as an impact measurement consultant. Educational use only. For {{business_name}} running {{program_name}} serving {{target_audience}}, create an impact framework: 3 outcomes, 2 indicators per outcome, data collection method, baseline questions to answer, and a short impact statement I can reuse in applications. Note which figures I must verify before submitting.',5,false),
('funder-alignment-check','Funder Alignment Check','Grants & Funding','Test fit before you spend hours applying.','Act as a grants advisor. Educational use only. Assess alignment between {{business_name}}, which does {{business_description}}, and {{funder_name}}, whose stated priorities are {{funder_priorities}}. Give a fit score out of 10, strongest alignment points, gaps, questions to ask the programme officer, and a go or no-go recommendation with reasoning.',6,false),
('grant-application-checklist','Grant Application Checklist','Grants & Funding','Never miss a required document or deadline again.','Act as a grants project manager. Educational use only. Build a submission checklist for {{business_name}} applying to {{funder_name}} by {{deadline}}. Include typical required documents, internal review steps, owner and due date columns, a formatting compliance pass, and a final 48-hour check. Remind me to confirm the exact requirement list with the funder guidelines.',7,false),
('investor-one-pager','Investor One-Pager','Grants & Funding','Summarise the opportunity on a single page.','Act as a startup fundraising advisor. Educational use only. Write a one-page investor summary for {{business_name}}, which offers {{product_service}} to {{target_audience}}. We are raising {{funding_amount}} to {{funding_purpose}}. Include problem, solution, traction, market size, business model, team, use of funds, and the ask. Mark every metric I must replace with verified numbers.',8,false),
-- Business Planning
('lean-business-plan','Lean Business Plan','Business Planning','A working plan you can finish in one sitting.','Act as a business planning consultant. Write a lean business plan for {{business_name}}, which sells {{product_service}} to {{target_audience}} in {{location}}. Cover: value proposition, customer segments, revenue streams, key activities, resources, partners, cost structure, marketing approach, and 3 milestones for the next 12 months.',1,true),
('executive-summary-writer','Executive Summary Writer','Business Planning','The one page decision-makers actually read.','Act as a business writer. Write an executive summary for {{business_name}}. We offer {{product_service}} to {{target_audience}} and our goal is {{primary_goal}}. Include the opportunity, our solution, market, competitive edge, business model, traction to date ({{traction}}), and what we need next. Under 400 words, confident and specific.',2,false),
('swot-analysis-builder','SWOT Analysis Builder','Business Planning','See your position clearly before you commit.','Act as a strategy consultant. Build a SWOT analysis for {{business_name}}, which sells {{product_service}} in the {{industry}} market. Context: {{current_situation}}. Give 5 items per quadrant, then convert them into 4 strategic moves: build on a strength, fix a weakness, capture an opportunity, and defend against a threat.',3,false),
('competitor-landscape-map','Competitor Landscape Map','Business Planning','Understand your market and where you win.','Act as a competitive analyst. Map the landscape for {{business_name}} against {{competitors}} in the {{industry}} market. Compare positioning, pricing approach, audience, strengths, weaknesses, and content strategy in a table. Then identify 3 gaps we can own and how to communicate them to {{target_audience}}.',4,false),
('revenue-model-planner','Revenue Model Planner','Business Planning','Design how the business actually makes money.','Act as a business model strategist. Design a revenue model for {{business_name}} selling {{product_service}} to {{target_audience}}. Propose 4 models (one-off, package, retainer, digital or passive), with pricing logic, effort level, and realistic monthly revenue at conservative volume. Recommend the best mix to reach {{revenue_goal}}.',5,false),
('startup-cost-estimator','Startup Cost Estimator','Business Planning','Know what launching really costs before you spend.','Act as a small business financial planner. Estimate startup costs for {{business_name}}, a {{business_type}} launching in {{location}} with a budget of {{budget}}. Break costs into one-time and recurring, mark each essential or optional, suggest lower-cost alternatives, and give a lean launch version plus a break-even estimate.',6,false),
('90-day-growth-roadmap','90-Day Growth Roadmap','Business Planning','Turn a big goal into weekly moves.','Act as a business coach. Build a 90-day roadmap for {{business_name}} to reach {{primary_goal}}. Current position: {{current_situation}}. Available time per week: {{weekly_hours}}. Organise it into 3 monthly themes with weekly priorities, deliverables, metrics, and one thing to stop doing each month.',7,false),
('sop-writer','Standard Operating Procedure Writer','Business Planning','Document a process so anyone can run it.','Act as an operations manager. Write a standard operating procedure for the process of {{process_name}} at {{business_name}}. Include purpose, scope, roles, tools required, numbered steps with detail, quality checks, common mistakes, and a handoff note so a new team member can run it without help.',8,false),
-- Emails
('cold-outreach-email','Cold Outreach Email','Emails','Open a conversation without sounding like a pitch.','Act as an outreach specialist. Write a cold email from {{sender_name}} at {{business_name}} to {{recipient_type}} about {{offer_or_reason}}. Keep it under 120 words: personalised opening, one line on the problem, one line of proof, a low-friction ask. Then give 2 subject line options and a 3-line follow-up.',1,true),
('client-proposal-email','Client Proposal Email','Emails','Send the proposal with confidence and clarity.','Act as a professional services consultant. Write a proposal email from {{business_name}} to {{client_name}} for {{project_scope}} at {{price}}. Include: recap of their goal, what is included, timeline, investment, next step, and a clear deadline. Confident, warm, and free of apology language.',2,false),
('follow-up-sequence','Follow-Up Sequence','Emails','Four polite nudges that get replies.','Act as a sales copywriter. Write a 4-email follow-up sequence from {{business_name}} to {{recipient_type}} who went quiet after {{last_interaction}}. Space them over 3 weeks. Each email should add value, stay short, and end with one clear question. Include the final graceful close-the-loop email.',3,false),
('welcome-email-sequence','Welcome Email Sequence','Emails','Turn new subscribers into buyers over 5 emails.','Act as an email marketing strategist. Write a 5-email welcome sequence for {{business_name}} for new subscribers who joined for {{lead_magnet}}. Audience: {{target_audience}}. Map each email to a purpose: deliver, story, teach, proof, offer {{product_service}}. Give subject lines, preview text, and body copy in a {{brand_tone}} tone.',4,false),
('payment-reminder-email','Payment Reminder Email','Emails','Chase an invoice without damaging the relationship.','Act as a business communication expert. Write 3 payment reminder emails from {{business_name}} to {{client_name}} for an unpaid invoice of {{amount}}, now {{days_overdue}} days overdue. Escalate tone gradually: friendly nudge, firm reminder, final notice with next steps. Stay professional and never emotional.',5,false),
('partnership-pitch-email','Partnership Pitch Email','Emails','Propose a collaboration that benefits both sides.','Act as a partnerships manager. Write a collaboration pitch from {{business_name}} to {{partner_name}} proposing {{collaboration_idea}}. Lead with what is in it for them, show audience overlap with {{target_audience}}, propose a simple first step, and keep it under 150 words. Add 2 subject lines.',6,false),
('difficult-client-response','Difficult Client Response','Emails','Handle complaints and scope creep calmly.','Act as a client relations expert. Write a response from {{business_name}} to {{client_name}} regarding {{situation}}. Acknowledge their concern, state facts without defensiveness, restate the agreement, offer a specific resolution, and set a clear boundary for next steps. Give a firmer alternative version too.',7,false),
('newsletter-email-draft','Newsletter Email Draft','Emails','A newsletter people open and read to the end.','Act as a newsletter writer. Write this week newsletter for {{business_name}} for {{target_audience}} about {{topic}}. Structure: subject line and preview text, personal opening, one main idea with a practical takeaway, a short resource or win, and a single call to action for {{product_service}}. Tone: {{brand_tone}}.',8,false),
-- Résumés
('resume-rewrite-ats','ATS-Ready Résumé Rewrite','Résumés','Rewrite your résumé to pass screening software.','Act as a certified résumé writer. Rewrite my résumé for a {{target_role}} role in {{industry}}. Here is my current content: {{current_resume}}. Optimise for applicant tracking systems: clean structure, relevant keywords from the job description {{job_description}}, achievement-led bullets with metrics, and a strong summary. Flag any gaps I should address.',1,true),
('achievement-bullet-builder','Achievement Bullet Builder','Résumés','Turn duties into results that impress.','Act as a career coach. Convert these job responsibilities into achievement bullets for a {{target_role}} application: {{responsibilities}}. Use the action-context-result format, add a metric placeholder where I need to insert a real number, and give 3 strength levels for each bullet from factual to high-impact.',2,false),
('professional-summary-writer','Professional Summary Writer','Résumés','Five strong lines at the top of your résumé.','Act as a résumé strategist. Write 4 versions of a professional summary for {{your_name}}, targeting a {{target_role}} role in {{industry}}, with {{years_experience}} years of experience and strengths in {{key_skills}}. Vary the emphasis: leadership, technical depth, results, and career change. Keep each under 60 words.',3,false),
('tailored-cover-letter','Tailored Cover Letter','Résumés','A cover letter written for one specific job.','Act as a hiring manager turned career coach. Write a cover letter for {{your_name}} applying for {{target_role}} at {{company_name}}. Job description: {{job_description}}. My relevant background: {{background}}. Open with a specific reason for this company, connect 3 requirements to my proof, and close with a confident next step. One page maximum.',4,false),
('linkedin-profile-optimizer','LinkedIn Profile Optimiser','Résumés','Make recruiters stop on your profile.','Act as a LinkedIn profile expert. Optimise the profile of {{your_name}}, a {{target_role}} in {{industry}} with strengths in {{key_skills}}. Deliver: 3 headline options, an About section in first person, 5 experience bullets, a skills list ordered by search value, and 3 content ideas to build visibility.',5,false),
('interview-answer-prep','Interview Answer Prep','Résumés','Practice the answers that decide the offer.','Act as an interview coach. Prepare me for a {{target_role}} interview at {{company_name}}. My background: {{background}}. Give 10 likely questions with a suggested structured answer outline for each, 3 behavioural answers using the situation-task-action-result format, and 5 smart questions for me to ask them.',6,false),
('career-change-resume','Career Change Résumé','Résumés','Reposition your experience for a new field.','Act as a career transition specialist. Reposition my experience for a move from {{current_field}} into {{target_role}}. My background: {{background}}. Identify transferable skills, translate industry jargon, propose a functional résumé structure, write a career-change summary, and suggest 3 ways to close credibility gaps.',7,false),
('salary-negotiation-script','Salary Negotiation Script','Résumés','Ask for more with evidence and composure.','Act as a compensation negotiation coach. Write a negotiation script for {{your_name}}, offered {{offered_salary}} for a {{target_role}} role, targeting {{target_salary}}. Include the opening line, evidence framing with my proof points {{achievements}}, responses to 4 pushbacks, a non-salary alternatives list, and a graceful close.',8,false),
-- Productivity
('weekly-priority-planner','Weekly Priority Planner','Productivity','Plan a week that moves the business forward.','Act as a productivity coach. Plan my week. My goal is {{primary_goal}}, my available working time is {{weekly_hours}}, and my current tasks are {{task_list}}. Identify the 3 highest-leverage priorities, schedule them into time blocks, batch the rest, name what to drop, and give a Friday review checklist.',1,true),
('time-audit-analysis','Time Audit Analysis','Productivity','Find out where the hours actually go.','Act as an efficiency consultant. Analyse my time log: {{time_log}}. My role is {{your_role}} and my goal is {{primary_goal}}. Categorise time into high value, maintenance, and waste; calculate rough percentages; identify the 3 biggest drains; and recommend what to automate, delegate, or delete.',2,false),
('task-batching-system','Task Batching System','Productivity','Group similar work to stop context switching.','Act as a workflow designer. Build a batching system for {{your_role}} at {{business_name}}. My recurring tasks are {{task_list}} and my working days are {{available_days}}. Group tasks into themed blocks, assign each to a day and energy level, and give rules for protecting deep work.',3,false),
('delegation-plan','Delegation Plan','Productivity','Decide what to hand off and how.','Act as an operations coach. Build a delegation plan for {{your_role}} at {{business_name}}. My current responsibilities are {{task_list}} and my budget for help is {{budget}}. Score each task on value, frequency, and difficulty to train; recommend keep, delegate, automate, or delete; and draft a handover brief for the top 3 to delegate.',4,false),
('focus-routine-builder','Focus Routine Builder','Productivity','A daily rhythm that protects your best hours.','Act as a performance coach. Design a daily routine for {{your_role}} whose peak energy is {{peak_energy_time}} and who has {{daily_hours}} of working time plus these commitments: {{commitments}}. Include a start-up ritual, deep work block, admin window, shutdown routine, and 3 rules for handling interruptions.',5,false),
('meeting-agenda-and-notes','Meeting Agenda & Notes','Productivity','Run tighter meetings with clear outcomes.','Act as a chief of staff. Create an agenda for a {{meeting_length}} meeting about {{meeting_topic}} with {{attendees}}. Include desired outcome, timed sections, pre-work, discussion questions, and a decisions and action items template with owners and due dates. Add 3 ways to keep it on time.',6,false),
('inbox-zero-system','Inbox Control System','Productivity','Stop living in your email.','Act as a systems consultant. Build an email management system for {{your_role}} at {{business_name}} who receives roughly {{email_volume}} emails a day. Include a folder or label structure, a 4-decision triage rule, twice-daily processing windows, 5 reusable reply templates, and rules for what never gets an email reply.',7,false),
('quarterly-goal-breakdown','Quarterly Goal Breakdown','Productivity','Break a 90-day goal into weekly action.','Act as an execution coach. Break down my quarterly goal of {{primary_goal}} for {{business_name}}. Current position: {{current_situation}}. Available time: {{weekly_hours}} per week. Give monthly milestones, weekly actions, leading and lagging metrics, likely obstacles with mitigations, and a simple weekly tracking table.',8,false);
